"""
Even Fibonacci numbers

https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

from itertools import takewhile
from functools import reduce


def fibonacci_sequence():
    prev, current = 1, 1
    yield prev
    yield current
    while True:
        prev, current = current, prev + current
        yield current


print(reduce(lambda a, b: a+b, filter(lambda n: n % 2 == 0, takewhile(
    lambda n: n <= 4000000, fibonacci_sequence()))))
